// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xenimcdufngewmpncjqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlbmltY2R1Zm5nZXdtcG5janF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NzE4MTksImV4cCI6MjA3MjE0NzgxOX0.2QXea9myVBETZncKwdLiLEHLq40prqornEVk_E1L3j4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});